name = "volleyball-stats"
main = "src/index.js"
compatibility_date = "2024-04-03"

assets = { directory = "public" }

[durable_objects]
bindings = [
  { name = "VOLLEYBALL_STATS_DO", class_name = "VolleyballStatsDurableObject" }
]

[[migrations]]
tag = "v1"
new_classes = ["VolleyballStatsDurableObject"]
