name = "volleyball-stats"
main = "src/index.ts"
compatibility_date = "2025-11-11"

[assets]
directory = "public"
binding = "ASSETS"

[vars]
debug = "true"
HOME_TEAM = "Stoney Creek"

[durable_objects]
bindings = [
  { name = "Match-DO", class_name = "MatchState" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "MatchState" ]
