name = "volleyball-stats"
main = "src/index.ts"
compatibility_date = "2025-12-5"

[assets]
directory = "public"
binding = "ASSETS"
serve_static = false

[vars]
debug = "true"
HOME_TEAM = "Stoney Creek"
APP_URL = "localhost"

[durable_objects]
bindings = [
  { name = "Match-DO", class_name = "MatchState" }
]

[[d1_databases]]
binding = "DB"
database_name = "volleyball_stats"
database_id = "00000000-0000-0000-0000-000000000000"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "MatchState" ]
