name = "volleyball-stats"
main = "src/index.js"
compatibility_date = "2025-11-7"

assets = { directory = "public" }
vars = { HOME_TEAM = "Home" }

[[durable_objects]]
name = "STATS_DB_DO"
class_name = "StatsDatabase"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["StatsDatabase"]
